#!/bin/bash
set -e

# 1. Dynamic Path Detection
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$PROJECT_ROOT/config"
WWW_DIR="$PROJECT_ROOT/www"

# Tor Data in Home (Standard)
TOR_DATA_DIR="/data/data/com.termux/files/home/.tor"
HIDDEN_SERVICE_DIR="$TOR_DATA_DIR/service"
HOSTNAME_FILE="$HIDDEN_SERVICE_DIR/hostname"

# Config Files
NGINX_CONFIG="$CONFIG_DIR/nginx.conf"
TOR_CONFIG="$CONFIG_DIR/torrc"

# System Paths
MIME_TYPES="/data/data/com.termux/files/usr/etc/nginx/mime.types"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== Starting Localhost Portfolio ===${NC}"
echo -e "Project Root: ${YELLOW}$PROJECT_ROOT${NC}"

# 2. Generate/Update Nginx Config with Correct Paths
echo -e "${YELLOW}Configuring Nginx...${NC}"
cat > "$NGINX_CONFIG" <<EOF
# AUTO-GENERATED BY start.sh
worker_processes 2;
pid $TOR_DATA_DIR/nginx.pid;
worker_rlimit_nofile 1024;

events {
    worker_connections 128; # Optimized for 150MB RAM limit
    use epoll;
    multi_accept on;
}

http {
    include $MIME_TYPES;
    default_type application/octet-stream;
    
    # Rate Limiting Zones
    limit_req_zone \$binary_remote_addr zone=portfolio_limit:10m rate=2r/s;
    limit_conn_zone \$binary_remote_addr zone=conn_limit:10m;

    # Performance Tuning
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 10; # Reduced for battery saving
    types_hash_max_size 2048;
    server_tokens off;
    
    # Async I/O
    aio threads;
    
    # Compression (Minimal set)
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
        text/css
        application/javascript
        image/svg+xml;

    # Caching
    expires 30d;
    add_header Cache-Control "public, immutable";
    
    # Logging (Disabled)
    access_log off;
    error_log stderr warn;
    
    server {
        listen 127.0.0.1:8080 http2; # HTTP/2 enabled
        root $WWW_DIR;
        index index.html;
        
        # Rate Limiting
        limit_req zone=portfolio_limit burst=5 nodelay;
        limit_conn conn_limit 5;
        
        # Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Content-Security-Policy "default-src 'self'; worker-src 'self'; connect-src 'self' wss:;" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
        
        location / {
            try_files \$uri \$uri/ =404;
        }
        
        # Health Check
        location /health {
            return 200 "OK\n";
        }
        
        location ~ /\. { deny all; }
    }
}
EOF

# 3. Acquire Wake Lock
echo -e "${YELLOW}Acquiring wake lock...${NC}"
termux-wake-lock

# 4. Start Tor
if ! pgrep -x "tor" > /dev/null; then
    echo -e "${YELLOW}Starting Tor...${NC}"
    # Ensure Tor data dir exists
    mkdir -p "$TOR_DATA_DIR"
    mkdir -p "$HIDDEN_SERVICE_DIR"
    chmod 700 "$TOR_DATA_DIR"
    chmod 700 "$HIDDEN_SERVICE_DIR"
    
    tor -f "$TOR_CONFIG" > /dev/null 2>&1 &
    
    # Wait for Onion Address
    echo -n "Waiting for onion address..."
    count=0
    while [ ! -f "$HOSTNAME_FILE" ]; do
        sleep 1
        echo -n "."
        count=$((count+1))
        if [ $count -ge 30 ]; then
            echo -e "\n${RED}Error: Timed out waiting for onion address.${NC}"
            killall tor
            exit 1
        fi
    done
    echo " Done."
fi

# 5. Start Nginx
if ! pgrep -x "nginx" > /dev/null; then
    echo -e "${YELLOW}Starting Nginx...${NC}"
    nginx -c "$NGINX_CONFIG"
fi

# 6. Start Monitor (Pass configs as args)
echo -e "${YELLOW}Starting Monitor Daemon...${NC}"
# Kill existing monitor if any
pkill -f "monitor.sh" || true
nohup "$SCRIPT_DIR/monitor.sh" "$TOR_CONFIG" "$NGINX_CONFIG" > /dev/null 2>&1 &

# 7. Display Status
ONION_ADDR=$(cat "$HOSTNAME_FILE")
echo -e "\n${GREEN}=== LOCALHOST ONLINE ===${NC}"
echo -e "Onion Address: ${GREEN}${ONION_ADDR}${NC}"
echo -e "Local Access:  http://127.0.0.1:8080"
echo -e "Project Root:  $PROJECT_ROOT"
